name       : puzzles
version    : '20221102'
release    : 13
source     :
    - https://www.chiark.greenend.org.uk/~sgtatham/puzzles/puzzles-20221102.289342e.tar.gz : 76a5c15b26383a5b0c8de8f7336c9fea60431189cc66da52f9cf800c8ab6c3d1
homepage   : https://www.chiark.greenend.org.uk/~sgtatham/puzzles/
license    : MIT
component  : games.puzzle
summary    : Simon Tatham's Portable Puzzle Collection
description: |
    This is a collection of small desktop toys, little games that you can pop up in a window and play for two or three minutes while you take a break from whatever else you were doing.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - imagemagick
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    for f in $installdir/usr/bin/*; do
        name=`basename $f`
        pzname=puzzle-$name

        # Some names are too generic
        mv $f $installdir/usr/bin/$pzname

        sed -e "s|<NAME>|${name^}|g; s|<PZNAME>|$pzname|g" $pkgfiles/template.desktop > $pzname.desktop
        rm $installdir/usr/share/applications/$name.desktop
        install -Dm00644 $pzname.desktop $installdir/usr/share/applications/$pzname.desktop
        mv $installdir/usr/share/pixmaps/$name-48d24.png $installdir/usr/share/pixmaps/$pzname.png
    done
