name       : puzzles
version    : '20201208'
release    : 3
source     :
    - https://www.chiark.greenend.org.uk/~sgtatham/puzzles/puzzles-20201208.84cb4c6.tar.gz : fd49aabdd7c7e521c990991dab59700a40719cca172113ac8df693afe11d284d
homepage   : https://www.chiark.greenend.org.uk/~sgtatham/puzzles/
license    : MIT
component  : games.puzzle
summary    : Simon Tatham's Portable Puzzle Collection
description: |
    This is a collection of small desktop toys, little games that you can pop up in a window and play for two or three minutes while you take a break from whatever else you were doing.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    for f in $installdir/usr/bin/*; do
        name=`basename $f`
        pzname=puzzle-$name

        # Some names are too generic
        mv $f $installdir/usr/bin/$pzname

        sed -e "s|<NAME>|${name^}|g; s|<PZNAME>|$pzname|g" $pkgfiles/template.desktop > $pzname.desktop
        install -Dm00644 $pzname.desktop $installdir/usr/share/applications/$pzname.desktop
        install -Dm00644 icons/$name-48d24.png $installdir/usr/share/icons/hicolor/48x48/apps/$pzname.png
    done
